### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by mglidden** [pburtchaell/react-input#6] opened 2016-12-12 21:24 UTC
Getting this error: `Uncaught TypeError: props.className is not a function(…)` on fields.js, line 13. Just cloned from master.

**Comment by pburtchaell** [comment] 2016-12-13 23:47
Thanks for the heads up @mglidden. I'll take a look.

**Comment by pburtchaell** [comment] 2016-12-21 03:28
This is resolved. Let me know if you have any further issues! Thanks. 😄

**Comment by alandickinson** [comment] 2017-01-15 17:56
I'm seeing this same error for line 33 in fields.js. `Uncaught TypeError: props.className is not a function`. Just installed via npm `npm install react-input`.

**Comment by Allend13** [comment] 2017-01-19 12:43
@alandickinson same for me :(

**Comment by pburtchaell** [comment] 2017-01-20 00:54
@alandickinson @Allend13 @mglidden Can you install `react-input@4.1.2` and confirm if the issue is resolved in this release? Tests pass for version 4.1.2.

**Comment by mglidden** [comment] 2017-01-20 16:24
Running the examples in the repo works for me

**Closed** 2017-02-02 21:10 UTC
Labels: bug
